import type { User, HealthMetric, Appointment, Medication, Article } from './types';
import placeholderData from './placeholder-images.json';

export const placeholderImages = placeholderData.placeholderImages;

export const mockUser: User = {
  id: 'user-123',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  age: 34,
  gender: 'Male',
  height: 180,
  weight: 75,
  bloodType: 'O+',
  emergencyContact: {
    name: 'Jane Doe',
    phone: '555-123-4567',
    relationship: 'Spouse',
  },
  medicalHistory: ['Asthma'],
  allergies: ['Pollen'],
};

export const mockHealthMetrics: HealthMetric[] = [
  {
    id: 'metric-1',
    userId: 'user-123',
    type: 'Blood Pressure',
    value: { systolic: 120, diastolic: 80 },
    unit: 'mmHg',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
  {
    id: 'metric-2',
    userId: 'user-123',
    type: 'Glucose',
    value: 95,
    unit: 'mg/dL',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
  {
    id: 'metric-3',
    userId: 'user-123',
    type: 'Weight',
    value: 75,
    unit: 'kg',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
  {
    id: 'metric-4',
    userId: 'user-123',
    type: 'BMI',
    value: 23.1,
    unit: '',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'appt-1',
    userId: 'user-123',
    providerId: 'prov-1',
    providerName: 'Dr. Emily Carter',
    providerSpecialty: 'Cardiologist',
    type: 'Telemedicine',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 7)),
    duration: 30,
    reason: 'Annual Checkup',
    status: 'Scheduled',
  },
  {
    id: 'appt-2',
    userId: 'user-123',
    providerId: 'prov-2',
    providerName: 'Dr. Ben Adams',
    providerSpecialty: 'Dermatologist',
    type: 'In-Person',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 14)),
    duration: 45,
    reason: 'Skin rash concern',
    status: 'Scheduled',
  },
    {
    id: 'appt-3',
    userId: 'user-123',
    providerId: 'prov-1',
    providerName: 'Dr. Emily Carter',
    providerSpecialty: 'Cardiologist',
    type: 'Telemedicine',
    dateTime: new Date(new Date().setDate(new Date().getDate() - 10)),
    duration: 30,
    reason: 'Follow-up',
    status: 'Completed',
  },
];

export const mockMedications: Medication[] = [
  {
    id: 'med-1',
    userId: 'user-123',
    name: 'Albuterol',
    dosage: '2 puffs',
    frequency: 'As needed for asthma',
    startDate: new Date('2022-01-01'),
    reminders: [],
    instructions: 'Use 15 minutes before exercise.',
  },
  {
    id: 'med-2',
    userId: 'user-123',
    name: 'Vitamin D',
    dosage: '1000 IU',
    frequency: 'Once daily',
    startDate: new Date('2023-01-01'),
    reminders: [new Date()],
    instructions: 'Take with food.',
  },
];

export const mockArticles: Article[] = [
  {
    id: 'article-1',
    title: 'Managing Diabetes Through Diet',
    category: 'Diabetes',
    summary: 'Learn how dietary changes can help manage blood sugar levels and improve your overall health.',
    content: 'Full article content here...',
    imageUrl: placeholderImages.find(p => p.id === 'article_diabetes')?.imageUrl || '',
    imageHint: 'healthy food',
    readTime: 5,
    author: 'Dr. Jane Smith',
    publishDate: new Date('2023-09-15'),
    tags: ['diabetes', 'diet', 'nutrition'],
  },
  {
    id: 'article-2',
    title: '5 Tips to Lower Your Blood Pressure',
    category: 'Hypertension',
    summary: 'Simple lifestyle changes you can make to reduce hypertension and improve cardiovascular health.',
    content: 'Full article content here...',
    imageUrl: placeholderImages.find(p => p.id === 'article_hypertension')?.imageUrl || '',
    imageHint: 'blood pressure',
    readTime: 4,
    author: 'Dr. John Davis',
    publishDate: new Date('2023-09-20'),
    tags: ['hypertension', 'blood pressure', 'lifestyle'],
  },
    {
    id: 'article-3',
    title: 'The Importance of Cardio for Heart Health',
    category: 'Heart Health',
    summary: 'Discover the benefits of cardiovascular exercise and how to incorporate it into your routine.',
    content: 'Full article content here...',
    imageUrl: placeholderImages.find(p => p.id === 'article_heart')?.imageUrl || '',
    imageHint: 'running park',
    readTime: 6,
    author: 'Dr. Emily Carter',
    publishDate: new Date('2023-09-25'),
    tags: ['heart health', 'exercise', 'cardio'],
  },
  {
    id: 'article-4',
    title: 'A Guide to Balanced Nutrition',
    category: 'Nutrition',
    summary: 'Understand the building blocks of a healthy diet and how to create balanced meals.',
    content: 'Full article content here...',
    imageUrl: placeholderImages.find(p => p.id === 'article_nutrition')?.imageUrl || '',
    imageHint: 'salad bowl',
    readTime: 7,
    author: 'Dr. Jane Smith',
    publishDate: new Date('2023-09-28'),
    tags: ['nutrition', 'diet', 'healthy eating'],
  },
];
