import type { User, HealthMetric, Appointment, Medication, Article, DashboardMetric, ArticleCategory } from './types';
import placeholderData from './placeholder-images.json';

export const placeholderImages = placeholderData.placeholderImages;

export const mockUser: User = {
  id: 'user-123',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  age: 34,
  gender: 'Male',
  height: 180,
  weight: 70,
  bloodType: 'O+',
  emergencyContact: {
    name: 'Jane Doe',
    phone: '555-123-4567',
    relationship: 'Spouse',
  },
  medicalHistory: ['Asthma'],
  allergies: ['Pollen'],
};

export const mockDashboardMetrics: DashboardMetric[] = [
  {
    type: 'Blood Pressure',
    value: '120/80',
    unit: 'mmHg',
    status: 'Normal',
    trend: 'stable',
  },
  {
    type: 'Glucose',
    value: '95',
    unit: 'mg/dL',
    status: 'Normal',
    trend: 'down',
  },
  {
    type: 'Weight',
    value: '70',
    unit: 'kg (BMI: 21.6)',
    status: 'Normal',
    trend: 'stable',
  },
  {
    type: 'Heart Rate',
    value: '72',
    unit: 'bpm',
    status: 'Normal',
    trend: 'up',
  },
]

export const mockHealthTips: string[] = [
    "Stay hydrated by drinking at least 8 glasses of water a day.",
    "Incorporate at least 30 minutes of moderate exercise into your daily routine.",
    "Aim for 7-9 hours of quality sleep each night for better recovery and mental health."
]

export const mockHealthMetrics: HealthMetric[] = [
  {
    id: 'metric-1',
    userId: 'user-123',
    type: 'Blood Pressure',
    value: { systolic: 120, diastolic: 80 },
    unit: 'mmHg',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
  {
    id: 'metric-2',
    userId: 'user-123',
    type: 'Glucose',
    value: 95,
    unit: 'mg/dL',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
  {
    id: 'metric-3',
    userId: 'user-123',
    type: 'Weight',
    value: 70,
    unit: 'kg',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
  {
    id: 'metric-4',
    userId: 'user-123',
    type: 'BMI',
    value: 21.6,
    unit: '',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
   {
    id: 'metric-5',
    userId: 'user-123',
    type: 'Heart Rate',
    value: 72,
    unit: 'bpm',
    timestamp: new Date('2023-10-01T08:00:00Z'),
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'appt-1',
    userId: 'user-123',
    providerId: 'prov-1',
    providerName: 'Dr. Emily Carter',
    providerSpecialty: 'Cardiologist',
    type: 'Telemedicine',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 7)),
    duration: 30,
    reason: 'Annual Checkup',
    status: 'Scheduled',
  },
  {
    id: 'appt-2',
    userId: 'user-123',
    providerId: 'prov-2',
    providerName: 'Dr. Ben Adams',
    providerSpecialty: 'Dermatologist',
    type: 'In-Person',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 14)),
    duration: 45,
    reason: 'Skin rash concern',
    status: 'Scheduled',
  },
    {
    id: 'appt-3',
    userId: 'user-123',
    providerId: 'prov-1',
    providerName: 'Dr. Emily Carter',
    providerSpecialty: 'Cardiologist',
    type: 'Telemedicine',
    dateTime: new Date(new Date().setDate(new Date().getDate() - 10)),
    duration: 30,
    reason: 'Follow-up',
    status: 'Completed',
  },
];

export const mockMedications: Medication[] = [
  {
    id: 'med-1',
    userId: 'user-123',
    name: 'Albuterol',
    dosage: '2 puffs',
    frequency: 'As needed for asthma',
    startDate: new Date('2022-01-01'),
    reminders: [],
    instructions: 'Use 15 minutes before exercise.',
  },
  {
    id: 'med-2',
    userId: 'user-123',
    name: 'Vitamin D',
    dosage: '1000 IU',
    frequency: 'Once daily',
    startDate: new Date('2023-01-01'),
    reminders: [new Date()],
    instructions: 'Take with food.',
  },
];

export const articleCategories: ArticleCategory[] = ['Diabetes', 'Hypertension', 'Heart Health', 'Nutrition', 'Exercise'];

export const mockArticles: Article[] = [
  {
    id: 'managing-diabetes-through-diet',
    title: 'Managing Diabetes Through Diet',
    category: 'Diabetes',
    summary: 'Learn how dietary changes can help manage blood sugar levels and improve your overall health.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    imageUrl: placeholderImages.find(p => p.id === 'article_diabetes')?.imageUrl || '',
    imageHint: 'healthy food',
    readTime: 5,
    author: 'Dr. Jane Smith',
    publishDate: new Date('2023-09-15'),
    tags: ['diabetes', 'diet', 'nutrition'],
  },
  {
    id: '5-tips-to-lower-your-blood-pressure',
    title: '5 Tips to Lower Your Blood Pressure',
    category: 'Hypertension',
    summary: 'Simple lifestyle changes you can make to reduce hypertension and improve cardiovascular health.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    imageUrl: placeholderImages.find(p => p.id === 'article_hypertension')?.imageUrl || '',
    imageHint: 'blood pressure',
    readTime: 4,
    author: 'Dr. John Davis',
    publishDate: new Date('2023-09-20'),
    tags: ['hypertension', 'blood pressure', 'lifestyle'],
  },
  {
    id: 'the-importance-of-cardio-for-heart-health',
    title: 'The Importance of Cardio for Heart Health',
    category: 'Heart Health',
    summary: 'Discover the benefits of cardiovascular exercise and how to incorporate it into your routine.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    imageUrl: placeholderImages.find(p => p.id === 'article_heart')?.imageUrl || '',
    imageHint: 'running park',
    readTime: 6,
    author: 'Dr. Emily Carter',
    publishDate: new Date('2023-09-25'),
    tags: ['heart health', 'exercise', 'cardio'],
  },
  {
    id: 'a-guide-to-balanced-nutrition',
    title: 'A Guide to Balanced Nutrition',
    category: 'Nutrition',
    summary: 'Understand the building blocks of a healthy diet and how to create balanced meals.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    imageUrl: placeholderImages.find(p => p.id === 'article_nutrition')?.imageUrl || '',
    imageHint: 'salad bowl',
    readTime: 7,
    author: 'Dr. Jane Smith',
    publishDate: new Date('2023-09-28'),
    tags: ['nutrition', 'diet', 'healthy eating'],
  },
  {
    id: 'beginner-guide-to-strength-training',
    title: "Beginner's Guide to Strength Training",
    category: 'Exercise',
    summary: 'Everything you need to know to start building muscle and strength, even as a complete beginner.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.',
    imageUrl: placeholderImages.find(p => p.id === 'article_exercise1')?.imageUrl || 'https://picsum.photos/seed/ex1/400/225',
    imageHint: 'person lifting weights',
    readTime: 8,
    author: 'Mike Anderson',
    publishDate: new Date('2023-10-02'),
    tags: ['exercise', 'strength training', 'fitness'],
  },
  {
    id: 'understanding-your-cholesterol-levels',
    title: 'Understanding Your Cholesterol Levels',
    category: 'Heart Health',
    summary: "A comprehensive guide to LDL, HDL, and triglycerides, and what they mean for your heart.",
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.',
    imageUrl: placeholderImages.find(p => p.id === 'article_cholesterol')?.imageUrl || 'https://picsum.photos/seed/chol/400/225',
    imageHint: 'blood test',
    readTime: 6,
    author: 'Dr. Emily Carter',
    publishDate: new Date('2023-10-05'),
    tags: ['cholesterol', 'heart health', 'lipids'],
  },
  {
    id: 'mindful-eating-for-a-healthier-life',
    title: 'Mindful Eating for a Healthier Life',
    category: 'Nutrition',
    summary: 'Learn to listen to your body\'s hunger cues and build a better relationship with food.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.',
    imageUrl: placeholderImages.find(p => p.id === 'article_mindful_eating')?.imageUrl || 'https://picsum.photos/seed/mindful/400/225',
    imageHint: 'person meditating food',
    readTime: 5,
    author: 'Dr. Sarah Chen',
    publishDate: new Date('2023-10-08'),
    tags: ['nutrition', 'mindfulness', 'eating habits'],
  },
  {
    id: 'benefits-of-high-intensity-interval-training',
    title: 'Benefits of High-Intensity Interval Training (HIIT)',
    category: 'Exercise',
    summary: 'Find out why HIIT is a time-efficient and effective way to boost your fitness.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.',
    imageUrl: placeholderImages.find(p => p.id === 'article_hiit')?.imageUrl || 'https://picsum.photos/seed/hiit/400/225',
    imageHint: 'person sprinting track',
    readTime: 5,
    author: 'Mike Anderson',
    publishDate: new Date('2023-10-11'),
    tags: ['exercise', 'hiit', 'cardio', 'fitness'],
  },
];
